<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v1/blob/main/myProspects_V20_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import datetime
import pytz
tz_NY = pytz.timezone('Asia/Kolkata')
datetime_NY = datetime.datetime.now(tz_NY)
print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

gen_output = 0

Run date time (IST): 2026-01-21 17:22:52

In [2]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.1)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.19.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [3]:
import pandas as pd
import numpy as np

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df
cols = ['Symbol', 'ATH%', 'PE', 'EPS', 'PB', 'MCap', 'ROCE%', 'ROE%',
       'Sales_Grwth%', 'Profit_Grwth%', 'MedPE',
       'Debt2EqR', 'PAT_12M', 'CFO_2_EBITDA%', 'CapType']
myscreen_df = get_myscreen_df()[cols]

# function to fetch screener data
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df
mypps_df = get_mypps_df()
my_analysis_df = pd.merge(myscreen_df, mypps_df, on='Symbol', how='left')
my_analysis_df['Conviction']  = my_analysis_df['Conviction'] + '-' + my_analysis_df['CapType']

stock_ids = my_analysis_df[my_analysis_df['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]['Symbol'].unique()

#mypf = mypf[mypf.Forecast.notnull()]
#stock_ids = mypf['Symbol'].unique()

stock_ids.sort()

In [4]:
# import libraries

%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
from tabulate import tabulate
import warnings
warnings.filterwarnings('ignore')
import pandas_datareader.data as web
import yfinance as yfin

In [5]:
import yfinance as yfin
def get_stock_v20(stock_symbol):
    #print(stock_symbol)
    stock_df = yfin.Ticker(stock_symbol).history(period='max')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Candle'] = 'R'
    stock_df.loc[stock_df['Close'] > stock_df['Open'], 'Candle'] = 'G'
    stock_df['Prev_Candle'] = stock_df['Candle'].shift(1)
    stock_df['Next_Candle'] = stock_df['Candle'].shift(-1)
    stock_df['Signal'] = 'NA'
    stock_df.loc[(stock_df['Candle'] != stock_df['Prev_Candle']) & (stock_df['Candle'] == 'G'), 'Signal'] = 'Start'
    stock_df.loc[(stock_df['Candle'] != stock_df['Next_Candle']) & (stock_df['Next_Candle'] == 'R') & (stock_df['Signal'] == 'NA'), 'Signal'] = 'End'
    stock_df.loc[(stock_df['Candle'] != stock_df['Next_Candle']) & (stock_df['Next_Candle'] == 'R') & (stock_df['Signal'] == 'Start'), 'Signal'] = 'Start/End'
    stock_df = stock_df[stock_df['Signal'] != 'NA']
    stock_df['Prev_Low'] = stock_df['Low'].shift(1)
    stock_df = stock_df[stock_df['Signal'] != 'Start']
    stock_df.loc[(stock_df['Signal'] == 'End'), 'Low'] = stock_df['Prev_Low']
    stock_df['Up%'] = round((stock_df['High'] - stock_df['Low'])*100/stock_df['Low'],2)
    stock_df = stock_df[stock_df['Up%'] > 20]
    stock_df['Current'] = yfin.Ticker(stock_symbol).history(period='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]['Close'].values[0]
    stock_df = stock_df[stock_df['Current'] < stock_df['Low']]
    stock_df['Stock'] = stock_symbol
    return stock_df

def get_v20():
    df_v20 = pd.DataFrame()
    for stock_id in stock_ids:
        #print(stock_id)
        df_tmp = get_stock_v20(stock_id+'.NS')
        df_tmp['MBQ'] = mypps_df[(mypps_df['Symbol']) == stock_id.upper()]['MBQ'].values[0]
        #df_v20 = df_v20.append(df_tmp)
        df_v20 = pd.concat([df_v20, df_tmp])

    return df_v20.sort_index()

In [6]:
cols = ['Stock', 'Up%', '200_SMA', 'Close' ,'MBQ']
df_v20_prospects = get_v20()[cols]

In [7]:
df_v20_prospects_200SMA = df_v20_prospects[(df_v20_prospects['Close'] <= df_v20_prospects['200_SMA'])]

In [8]:
df_v20_prospects_V40N = df_v20_prospects[(df_v20_prospects['MBQ'].str.contains('X40', na=False)) | (df_v20_prospects['MBQ'].str.contains('X40N', na=False))]

In [9]:
df_final_v20 = pd.concat([df_v20_prospects_V40N.reset_index(), df_v20_prospects_200SMA.reset_index()])
df_final_v20.set_index("Date", inplace = True)
df_final_v20.drop_duplicates().sort_index()

,Stock,Up%,200_SMA,Close,MBQ
Date,,,,,
2017-11-09 00:00:00+05:30,TEAMLEASE.NS,20.31,1267.0,1886.849976,X40N
2017-11-22 00:00:00+05:30,TEAMLEASE.NS,21.13,1312.0,2082.300049,X40N
2017-12-26 00:00:00+05:30,TEAMLEASE.NS,27.81,1456.0,2468.850098,X40N
2018-04-25 00:00:00+05:30,TEAMLEASE.NS,36.64,1898.0,2714.050049,X40N
2018-09-25 00:00:00+05:30,TEAMLEASE.NS,28.97,2491.0,2527.399902,X40N
2018-12-12 00:00:00+05:30,QUESS.NS,20.34,906.0,634.216614,XY24
2020-03-13 00:00:00+05:30,QUESS.NS,28.49,475.0,410.689880,XY24
2020-03-13 00:00:00+05:30,TEAMLEASE.NS,25.88,2708.0,2314.399902,X40N
2020-03-20 00:00:00+05:30,BATAINDIA.NS,29.50,1497.0,1157.368774,X40
2020-03-26 00:00:00+05:30,BATAINDIA.NS,22.91,1493.0,1155.022705,X40
2020-03-30 00:00:00+05:30,RELAXO.NS,21.80,543.0,585.871399,X40N
2020-03-31 00:00:00+05:30,TEAMLEASE.NS,26.42,2639.0,1627.099976,X40N
2020-06-03 00:00:00+05:30,TEAMLEASE.NS,29.73,2365.0,1789.300049,X40N
2020-06-04 00:00:00+05:30,RELAXO.NS,22.37,585.0,763.569031,X40N
2021-02-09 00:00:00+05:30,TEAMLEASE.NS,38.48,2188.0,3577.149902,X40N
2022-02-03 00:00:00+05:30,TEAMLEASE.NS,20.78,4015.0,4627.649902,X40N
2022-02-10 00:00:00+05:30,AWL.NS,70.15,325.0,386.250000,XY24/X40N
2022-03-02 00:00:00+05:30,AWL.NS,28.85,354.0,382.299988,XY24/X40N
2022-03-29 00:00:00+05:30,AWL.NS,29.95,367.0,499.950012,XY24/X40N
2022-04-18 00:00:00+05:30,AWL.NS,21.42,422.0,667.950012,XY24/X40N
2022-04-27 00:00:00+05:30,AWL.NS,26.38,464.0,841.000000,XY24/X40N
2022-05-23 00:00:00+05:30,AWL.NS,36.36,512.0,736.599976,XY24/X40N
2023-05-23 00:00:00+05:30,AWL.NS,33.52,566.0,488.700012,XY24/X40N
2023-12-18 00:00:00+05:30,TEAMLEASE.NS,32.14,2400.0,2925.949951,X40N
2024-02-23 00:00:00+05:30,JIOFIN.NS,27.62,238.0,333.430084,XY24/X40N
2024-05-16 00:00:00+05:30,HONAUT.NS,35.74,39108.0,55480.082031,X40N
2024-07-29 00:00:00+05:30,TEAMLEASE.NS,21.84,2916.0,3444.550049,X40N
2024-09-17 00:00:00+05:30,BAJAJHFL.NS,24.32,173.0,181.500000,X40N
2024-10-09 00:00:00+05:30,BAJAJHFL.NS,22.45,158.0,155.270004,X40N
2024-12-05 00:00:00+05:30,CAMS.NS,20.05,754.0,1032.142334,X40N
2024-12-30 00:00:00+05:30,BAJAJHLDNG.NS,21.27,9424.0,12543.257812,X40/X5K
2025-04-22 00:00:00+05:30,DIXON.NS,31.93,14433.0,16667.582031,X40N
2025-04-22 00:00:00+05:30,HAVELLS.NS,20.46,1704.0,1658.323486,X40
2025-05-19 00:00:00+05:30,BAJAJHLDNG.NS,21.95,10938.0,13876.155273,X40/X5K

In [10]:
df_final_v20.drop_duplicates().sort_index().tail(20)

,Stock,Up%,200_SMA,Close,MBQ
Date,,,,,
2021-02-09 00:00:00+05:30,TEAMLEASE.NS,38.48,2188.0,3577.149902,X40N
2022-02-03 00:00:00+05:30,TEAMLEASE.NS,20.78,4015.0,4627.649902,X40N
2022-02-10 00:00:00+05:30,AWL.NS,70.15,325.0,386.250000,XY24/X40N
2022-03-02 00:00:00+05:30,AWL.NS,28.85,354.0,382.299988,XY24/X40N
2022-03-29 00:00:00+05:30,AWL.NS,29.95,367.0,499.950012,XY24/X40N
2022-04-18 00:00:00+05:30,AWL.NS,21.42,422.0,667.950012,XY24/X40N
2022-04-27 00:00:00+05:30,AWL.NS,26.38,464.0,841.000000,XY24/X40N
2022-05-23 00:00:00+05:30,AWL.NS,36.36,512.0,736.599976,XY24/X40N
2023-05-23 00:00:00+05:30,AWL.NS,33.52,566.0,488.700012,XY24/X40N
2023-12-18 00:00:00+05:30,TEAMLEASE.NS,32.14,2400.0,2925.949951,X40N
2024-02-23 00:00:00+05:30,JIOFIN.NS,27.62,238.0,333.430084,XY24/X40N
2024-05-16 00:00:00+05:30,HONAUT.NS,35.74,39108.0,55480.082031,X40N
2024-07-29 00:00:00+05:30,TEAMLEASE.NS,21.84,2916.0,3444.550049,X40N
2024-09-17 00:00:00+05:30,BAJAJHFL.NS,24.32,173.0,181.500000,X40N
2024-10-09 00:00:00+05:30,BAJAJHFL.NS,22.45,158.0,155.270004,X40N
2024-12-05 00:00:00+05:30,CAMS.NS,20.05,754.0,1032.142334,X40N
2024-12-30 00:00:00+05:30,BAJAJHLDNG.NS,21.27,9424.0,12543.257812,X40/X5K
2025-04-22 00:00:00+05:30,DIXON.NS,31.93,14433.0,16667.582031,X40N
2025-04-22 00:00:00+05:30,HAVELLS.NS,20.46,1704.0,1658.323486,X40
2025-05-19 00:00:00+05:30,BAJAJHLDNG.NS,21.95,10938.0,13876.155273,X40/X5K

In [11]:
df_v20_prospects['MBQ'].value_counts()

MBQ
X40N         19
XY24          8
XY24/X40N     8
X40           3
X40/X5K       2
AR            1
XY25/X5K      1
Name: count, dtype: int64